#!/bin/bash

# Certificate API - Bulk Insert Sample Test
# This script sends 10 sample certificate records to the API

API_URL="http://localhost/api/certificates/store"

# Sample data with 10 certificates
curl -X POST "http://localhost/api/certificates/store" \
  -H "Content-Type: application/json" \
  -H "Accept: application/json" \
  -d '{
  "certificates": [
    {
      "master_policy_number": "22N38840",
      "status": "Active",
      "item_number": "ITEM001",
      "gr_lr_number": "GR2025001",
      "gr_lr_date": "2025-01-15",
      "insured_commodity": "Electronics",
      "cargo_value": 150000,
      "gross_premium": 1200.5,
      "gst_premium": 216.09,
      "total_premium": 1416.59,
      "insured_name": "ABC Electronics Ltd",
      "cc_mail": "finance@abcelectronics.com",
      "insured_address": "123 MG Road, Bangalore, Karnataka 560001",
      "insured_mobile": "9876543210",
      "insured_email": "info@abcelectronics.com",
      "voyage_from": "Mumbai, Maharashtra",
      "voyage_to": "Bangalore, Karnataka",
      "invoice_number": "INV2025-001",
      "invoice_date": "2025-01-14",
      "declaration_id": "DECL001",
      "description": "Electronic goods shipment",
      "master_policy_type": "Marine",
      "policy_source": "Direct",
      "vb_64": "VB64-001",
      "is_cancelled": false
    },
    {
      "master_policy_number": "22N38840",
      "status": "Active",
      "item_number": "ITEM002",
      "gr_lr_number": "GR2025002",
      "gr_lr_date": "2025-01-16",
      "insured_commodity": "Textiles",
      "cargo_value": 200000,
      "insured_name": "Fashion Hub Pvt Ltd",
      "cc_mail": "accounts@fashionhub.com",
      "insured_address": "456 Fashion Street, Mumbai, Maharashtra 400001",
      "insured_mobile": "9876543211",
      "insured_email": "info@fashionhub.com",
      "voyage_from": "Delhi, Delhi",
      "voyage_to": "Mumbai, Maharashtra",
      "invoice_number": "INV2025-002",
      "invoice_date": "2025-01-15",
      "declaration_id": "DECL002",
      "description": "Textile cargo shipment",
      "master_policy_type": "Marine",
      "policy_source": "Broker",
      "vb_64": "VB64-002",
      "is_cancelled": false,
      "is_intracity": false,
      "is_intercity": true
    },
    {
      "master_policy_number": "22N38840",
      "status": "Active",
      "item_number": "ITEM003",
      "gr_lr_number": "GR2025003",
      "gr_lr_date": "2025-01-17",
      "insured_commodity": "Furniture",
      "cargo_value": 180000,
      "insured_name": "HomeStyle Furniture Co",
      "cc_mail": "billing@homestyle.com",
      "insured_address": "789 Decor Avenue, Pune, Maharashtra 411001",
      "insured_mobile": "9876543212",
      "insured_email": "contact@homestyle.com",
      "voyage_from": "Pune, Maharashtra",
      "voyage_to": "Hyderabad, Telangana",
      "invoice_number": "INV2025-003",
      "invoice_date": "2025-01-16",
      "declaration_id": "DECL003",
      "description": "Furniture goods transit",
      "master_policy_type": "Marine",
      "policy_source": "Direct",
      "vb_64": "VB64-003",
      "is_cancelled": false,
      "is_intracity": false,
      "is_intercity": true
    },
    {
      "master_policy_number": "22N38840",
      "status": "Active",
      "item_number": "ITEM004",
      "gr_lr_number": "GR2025004",
      "gr_lr_date": "2025-01-18",
      "insured_commodity": "Machinery Parts",
      "cargo_value": 350000,
      "insured_name": "Industrial Solutions Ltd",
      "cc_mail": "finance@industrial.com",
      "insured_address": "321 Industry Park, Chennai, Tamil Nadu 600001",
      "insured_mobile": "9876543213",
      "insured_email": "sales@industrial.com",
      "voyage_from": "Chennai, Tamil Nadu",
      "voyage_to": "Coimbatore, Tamil Nadu",
      "invoice_number": "INV2025-004",
      "invoice_date": "2025-01-17",
      "declaration_id": "DECL004",
      "description": "Industrial machinery parts",
      "master_policy_type": "Marine",
      "policy_source": "Broker",
      "vb_64": "VB64-004",
      "is_cancelled": false,
      "is_intracity": false,
      "is_intercity": true
    },
    {
      "master_policy_number": "22N38840",
      "status": "Active",
      "item_number": "ITEM005",
      "gr_lr_number": "GR2025005",
      "gr_lr_date": "2025-01-19",
      "insured_commodity": "Pharmaceuticals",
      "cargo_value": 500000,
      "insured_name": "HealthCare Pharma Pvt Ltd",
      "cc_mail": "accounts@healthcare.com",
      "insured_address": "555 Medical Complex, Ahmedabad, Gujarat 380001",
      "insured_mobile": "9876543214",
      "insured_email": "info@healthcare.com",
      "voyage_from": "Ahmedabad, Gujarat",
      "voyage_to": "Surat, Gujarat",
      "invoice_number": "INV2025-005",
      "invoice_date": "2025-01-18",
      "declaration_id": "DECL005",
      "description": "Pharmaceutical products",
      "master_policy_type": "Marine",
      "policy_source": "Direct",
      "vb_64": "VB64-005",
      "is_cancelled": false,
      "is_intracity": false,
      "is_intercity": true
    },
    {
      "master_policy_number": "22N38840",
      "status": "Active",
      "item_number": "ITEM006",
      "gr_lr_number": "GR2025006",
      "gr_lr_date": "2025-01-20",
      "insured_commodity": "Consumer Goods",
      "cargo_value": 120000,
      "insured_name": "Retail Express Ltd",
      "cc_mail": "billing@retailexpress.com",
      "insured_address": "777 Shopping Plaza, Kolkata, West Bengal 700001",
      "insured_mobile": "9876543215",
      "insured_email": "support@retailexpress.com",
      "voyage_from": "Kolkata, West Bengal",
      "voyage_to": "Guwahati, Assam",
      "invoice_number": "INV2025-006",
      "invoice_date": "2025-01-19",
      "declaration_id": "DECL006",
      "description": "FMCG goods shipment",
      "master_policy_type": "Marine",
      "policy_source": "Broker",
      "vb_64": "VB64-006",
      "is_cancelled": false,
      "is_intracity": false,
      "is_intercity": true
    },
    {
      "master_policy_number": "22N38840",
      "status": "Active",
      "item_number": "ITEM007",
      "gr_lr_number": "GR2025007",
      "gr_lr_date": "2025-01-21",
      "insured_commodity": "Automobile Parts",
      "cargo_value": 280000,
      "insured_name": "Auto Components India",
      "cc_mail": "finance@autocomponents.com",
      "insured_address": "888 Auto Hub, Jaipur, Rajasthan 302001",
      "insured_mobile": "9876543216",
      "insured_email": "contact@autocomponents.com",
      "voyage_from": "Jaipur, Rajasthan",
      "voyage_to": "Ludhiana, Punjab",
      "invoice_number": "INV2025-007",
      "invoice_date": "2025-01-20",
      "declaration_id": "DECL007",
      "description": "Auto spare parts",
      "master_policy_type": "Marine",
      "policy_source": "Direct",
      "vb_64": "VB64-007",
      "is_cancelled": false,
      "is_intracity": false,
      "is_intercity": true
    },
    {
      "master_policy_number": "22N38840",
      "status": "Active",
      "item_number": "ITEM008",
      "gr_lr_number": "GR2025008",
      "gr_lr_date": "2025-01-22",
      "insured_commodity": "Agricultural Products",
      "cargo_value": 95000,
      "insured_name": "FarmFresh Produce Ltd",
      "cc_mail": "admin@farmfresh.com",
      "insured_address": "999 Green Valley, Nashik, Maharashtra 422001",
      "insured_mobile": "9876543217",
      "insured_email": "sales@farmfresh.com",
      "voyage_from": "Nashik, Maharashtra",
      "voyage_to": "Nagpur, Maharashtra",
      "invoice_number": "INV2025-008",
      "invoice_date": "2025-01-21",
      "declaration_id": "DECL008",
      "description": "Fresh produce shipment",
      "master_policy_type": "Marine",
      "policy_source": "Broker",
      "vb_64": "VB64-008",
      "is_cancelled": false,
      "is_intracity": false,
      "is_intercity": true
    },
    {
      "master_policy_number": "22N38840",
      "status": "Active",
      "item_number": "ITEM009",
      "gr_lr_number": "GR2025009",
      "gr_lr_date": "2025-01-23",
      "insured_commodity": "Building Materials",
      "cargo_value": 420000,
      "insured_name": "Construction Supplies Co",
      "cc_mail": "accounts@construction.com",
      "insured_address": "111 Builder Street, Indore, Madhya Pradesh 452001",
      "insured_mobile": "9876543218",
      "insured_email": "info@construction.com",
      "voyage_from": "Indore, Madhya Pradesh",
      "voyage_to": "Bhopal, Madhya Pradesh",
      "invoice_number": "INV2025-009",
      "invoice_date": "2025-01-22",
      "declaration_id": "DECL009",
      "description": "Building material transit",
      "master_policy_type": "Marine",
      "policy_source": "Direct",
      "vb_64": "VB64-009",
      "is_cancelled": false,
      "is_intracity": false,
      "is_intercity": true
    },
    {
      "master_policy_number": "22N38840",
      "status": "Active",
      "item_number": "ITEM010",
      "gr_lr_number": "GR2025010",
      "gr_lr_date": "2025-01-24",
      "insured_commodity": "Cosmetics",
      "cargo_value": 165000,
      "gross_premium": 1800.75,
      "gst_premium": 324.14,
      "total_premium": 2124.89,
      "insured_name": "Beauty Products India",
      "cc_mail": "billing@beautyproducts.com",
      "insured_address": "222 Beauty Lane, Lucknow, Uttar Pradesh 226001",
      "insured_mobile": "9876543219",
      "insured_email": "contact@beautyproducts.com",
      "voyage_from": "Lucknow, Uttar Pradesh",
      "voyage_to": "Kanpur, Uttar Pradesh",
      "invoice_number": "INV2025-010",
      "invoice_date": "2025-01-23",
      "declaration_id": "DECL010",
      "description": "Cosmetic products shipment",
      "master_policy_type": "Marine",
      "policy_source": "Broker",
      "vb_64": "VB64-010",
      "is_cancelled": false
    }
  ]
}'
